exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: 1,
      first_name: "John",
      last_name: "Doe",
      username: "johndoe",
      email: "john.doe@example.com",
      password: "$2a$10$gjfW9M2SQSN9MDyZkI/1uu15.Vbc5v0bALboCCqeB34M.NZkuiLGS",
      // password: "password123",
    },
    {
      id: 2,
      first_name: "Jane",
      last_name: "Smith",
      username: "janesmith",
      email: "jane.smith@example.com",
      password: "$2a$10$LLgoc8ZK/8aw3PKU/6kpruYqiHyGNdDwqeBc4lROeduc.9L5r5mc2",
      // password: "password456",
    },
    {
      id: 3,
      first_name: "Michael",
      last_name: "Johnson",
      username: "michaeljohnson",
      email: "michael.johnson@example.com",
      // password: "password789",
      password: "$2a$10$P0v8qVQlRhhjCfozw5VXw.EzcMWkhB190ASdrECkCjSzR.6Ct6oFC",
    },
    {
      id: 4,
      first_name: "Sarah",
      last_name: "Williams",
      username: "sarahwilliams",
      email: "sarah.williams@example.com",
      // password: "passwordabc",
      password: "$2a$10$ztpQn2hDilEjix2AalzzkOhUBWpNe0CkQthZIXx7zzLQYVVJRNAOW",
    },
    {
      id: 5,
      first_name: "David",
      last_name: "Brown",
      username: "davidbrown",
      email: "david.brown@example.com",
      // password: "passworddef",
      password: "$2a$10$IRhpt9fTH.HfIFH02837E.ApndtUargf8AjyQ6bL8aDpgzEzXcCbm",
    },
    {
      id: 6,
      first_name: "Emily",
      last_name: "Taylor",
      username: "emilytaylor",
      email: "emily.taylor@example.com",
      // password: "passwordghi",
      password: "$2a$10$0YJcH2yhg5EnRVZDXtXQ1es14M/D3ESyFCLP8l0XeXcXQK.PYnMOe",
    },
    {
      id: 7,
      first_name: "Daniel",
      last_name: "Anderson",
      username: "danielanderson",
      email: "daniel.anderson@example.com",
      // password: "passwordjkl",
      password: "$2a$10$qMfCELCRYN.TzsYppMh2Fuf5/ZYKV14PEvmRnzYhlHBBLiXiUcJja",
    },
    {
      id: 8,
      first_name: "Olivia",
      last_name: "Thomas",
      username: "oliviathomas",
      email: "olivia.thomas@example.com",
      // password: "passwordmno",
      password: "$2a$10$bj837g1fmcoxg1q0O9Uqi..OaoRPbcYLDKQQrcfc.K2iHQnIEXNEq",
    },
    {
      id: 9,
      first_name: "Matthew",
      last_name: "Miller",
      username: "matthewmiller",
      email: "matthew.miller@example.com",
      password: "$2a$10$wpPb5L7MdPw/QC0wpEu7VOy8cps7S0edOlXMkyNgR5EO8ui48GpCO",
      // password: "passwordpqr",
    },
    {
      id: 10,
      first_name: "Ava",
      last_name: "Davis",
      username: "avadavis",
      email: "ava.davis@example.com",
      // password: "passwordstu",
      password: "$2a$10$rDogvt4lgjz5ZFm3dj2RQ.F8e4BA.efrXqvL7WwY03OTbzd2lzzeC",
    },
  ]);
};
