exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      id: 1,
      first_name: "John",
      last_name: "Doe",
      username: "johndoe",
      email: "john.doe@example.com",
      password: "password123",
    },
    {
      id: 2,
      first_name: "Jane",
      last_name: "Smith",
      username: "janesmith",
      email: "jane.smith@example.com",
      password: "password456",
    },
    {
      id: 3,
      first_name: "Michael",
      last_name: "Johnson",
      username: "michaeljohnson",
      email: "michael.johnson@example.com",
      password: "password789",
    },
    {
      id: 4,
      first_name: "Sarah",
      last_name: "Williams",
      username: "sarahwilliams",
      email: "sarah.williams@example.com",
      password: "passwordabc",
    },
    {
      id: 5,
      first_name: "David",
      last_name: "Brown",
      username: "davidbrown",
      email: "david.brown@example.com",
      password: "passworddef",
    },
    {
      id: 6,
      first_name: "Emily",
      last_name: "Taylor",
      username: "emilytaylor",
      email: "emily.taylor@example.com",
      password: "passwordghi",
    },
    {
      id: 7,
      first_name: "Daniel",
      last_name: "Anderson",
      username: "danielanderson",
      email: "daniel.anderson@example.com",
      password: "passwordjkl",
    },
    {
      id: 8,
      first_name: "Olivia",
      last_name: "Thomas",
      username: "oliviathomas",
      email: "olivia.thomas@example.com",
      password: "passwordmno",
    },
    {
      id: 9,
      first_name: "Matthew",
      last_name: "Miller",
      username: "matthewmiller",
      email: "matthew.miller@example.com",
      password: "passwordpqr",
    },
    {
      id: 10,
      first_name: "Ava",
      last_name: "Davis",
      username: "avadavis",
      email: "ava.davis@example.com",
      password: "passwordstu",
    },
  ]);
};
